### ISSUE TITLE
Basic HTTP Authentification Parsing

### ISSUE THREAD

**Issue by ghost** [Amund/noop#1]
I'm building a RESTLESS API with Noop and i would need a easy way to parse my Base64 authentification header. Could you make it happen soon.

**Comment by Amund** [comment]
Parsing ? You don't have your credentials in $_SERVER ?

You can put something like that in `index.php`, just before `noop::start()`

``` php
if( isset( $_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW'] ) ) {
    my_auth_func( $_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW'] );
}
noop::start();
```
